version: 1
filesystem_policy:
  include_workdir: true
  read_only:
    - /usr
    - /lib
    - /etc
    - /proc
    - /sys/fs/cgroup
    - /sys/devices/system/cpu
    - /dev/urandom
    - /dev/random
  read_write:
    - /home/node
    - /tmp
    - /dev/null
    - /dev/shm
landlock:
  compatibility: hard_requirement
process: {}
network_policies: {}
