server:
    username: ""
    chroot: ""
    directory: "/etc/unbound"
    pidfile: ""
    use-syslog: no
    logfile: ""
    verbosity: 0
    log-queries: no
    log-replies: no
    log-servfail: no
    log-local-actions: no
    statistics-interval: 0
    hide-identity: yes
    hide-version: yes
    do-ip6: no
    do-udp: yes
    do-tcp: yes
    access-control: 0.0.0.0/0 refuse
    access-control: 127.0.0.0/8 refuse
    access-control: ::0/0 refuse
    module-config: "iterator"
    num-threads: 1
    num-queries-per-thread: 128
    outgoing-range: 256
    incoming-num-tcp: 16
    outgoing-num-tcp: 16
    msg-cache-size: 4m
    rrset-cache-size: 8m
    edns-buffer-size: 1232
    cache-max-ttl: 300
    cache-max-negative-ttl: 60
    serve-expired: no
    prefetch: no

    local-zone: "localhost." always_refuse
    private-address: 0.0.0.0/8
    private-address: 10.0.0.0/8
    private-address: 100.64.0.0/10
    private-address: 127.0.0.0/8
    private-address: 169.254.0.0/16
    private-address: 172.16.0.0/12
    private-address: 192.0.0.0/24
    private-address: 192.0.2.0/24
    private-address: 192.88.99.0/24
    private-address: 192.168.0.0/16
    private-address: 198.18.0.0/15
    private-address: 198.51.100.0/24
    private-address: 203.0.113.0/24
    private-address: 224.0.0.0/4
    private-address: 240.0.0.0/4
    private-address: ::/3
    private-address: 4000::/2
    private-address: 8000::/1
    private-address: 2001::/23
    private-address: 2001:db8::/32
    private-address: 2002::/16
    private-address: 3fff::/20

remote-control:
    control-enable: no

include-toplevel: "/etc/unbound/deployment.conf"
