export const localLogNames = [
  "controller",
  "application",
  "widgets",
  "companion",
  "postgres",
  "models",
  "models-database",
  "browser-relay",
  "browser",
  "browser-egress",
  "browser-node",
  "browser-node-ingress",
  "browser-node-dns",
] as const;
